# Generated by Django 3.2.5 on 2021-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createapimodel',
            name='trigger',
            field=models.BooleanField(default=False),
        ),
    ]
