# Generated by Django 3.2.5 on 2021-07-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createapimodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
